# Generated by Django 2.2.7 on 2019-11-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20191108_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouruser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
